version: '3.4'

networks:
    modaversatilapp:

services:
  modaversatildb:
    container_name: modaversatildb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Q2w3e4r
      - MSSQL_SA_PASSWORD=1Q2w3e4r      
      - MSSQL_PID=Express
    networks:
       - modaversatilapp
    volumes:  
      - sqlserver_data:/var/opt/mssql  
  modaversatil:
    container_name: modaversatil
    image: ${DOCKER_REGISTRY-}modaversatil
    build:
      context: .
      dockerfile: ModaVersatil/Dockerfile
    ports:
      - 8081:81      
      - 57656:444        
    depends_on:
      - modaversatildb
    environment:
      - DB_HOST=modaversatildb
      - DB_NAME=ModaVersatil 
      - DB_SA_USER_ID=sa
      - DB_SA_PASSWORD=1Q2w3e4r
      - DB_PORT=1433
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:444;http://+:81
    networks:
      - modaversatilapp
volumes:
  sqlserver_data: 
